name: Alberto Erazo
favicon: null
layout_spectrum: 0.9404259391594678
typography_spectrum: 0.36590645043179393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.45819152472540736
  lightness: 0.6246654621791095
  saturation: 0.6186319200787693
  rhythmicContrast: 0.25080206617712975
purpose: []
