name: Alberto Erazo
favicon: null
layout_spectrum: 0.76535
typography_spectrum: 0.15298
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#56b2f4'
    - '#1879c4'
    - '#9ad2f8'
    - '#02131e'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
